#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_ENEMY_2 (ID_TEX_ENEMY + 1)
#define ID_TEX_ENEMY_FLIP (ID_TEX_ENEMY + 2)
#define ID_TEX_ENEMY_2_FLIP (ID_TEX_ENEMY + 3)
#define ID_TEX_MISC 20
#define ID_TEX_ENVI 30	

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

//tanooki state

#define ID_SPRITE_MARIO_TANOOKI (ID_SPRITE_MARIO + 4000)
#define ID_SPRITE_MARIO_TANOOKI_IDLE (ID_SPRITE_MARIO_TANOOKI + 100)
#define ID_SPRITE_MARIO_TANOOKI_IDLE_LEFT (ID_SPRITE_MARIO_TANOOKI_IDLE + 10)
#define ID_SPRITE_MARIO_TANOOKI_IDLE_RIGHT (ID_SPRITE_MARIO_TANOOKI_IDLE + 20)

#define ID_SPRITE_MARIO_TANOOKI_WALKING (ID_SPRITE_MARIO_TANOOKI + 200)
#define ID_SPRITE_MARIO_TANOOKI_WALKING_LEFT (ID_SPRITE_MARIO_TANOOKI_WALKING + 10)
#define ID_SPRITE_MARIO_TANOOKI_WALKING_RIGHT (ID_SPRITE_MARIO_TANOOKI_WALKING + 20)
#define ID_SPRITE_MARIO_TANOOKI_RUNNING (ID_SPRITE_MARIO_TANOOKI + 300)
#define ID_SPRITE_MARIO_TANOOKI_RUNNING_LEFT (ID_SPRITE_MARIO_TANOOKI_RUNNING + 10)
#define ID_SPRITE_MARIO_TANOOKI_RUNNING_RIGHT (ID_SPRITE_MARIO_TANOOKI_RUNNING + 20)
#define ID_SPRITE_MARIO_TANOOKI_JUMP (ID_SPRITE_MARIO_TANOOKI + 400)
#define ID_SPRITE_MARIO_TANOOKI_JUMP_WALK (ID_SPRITE_MARIO_TANOOKI_JUMP + 10)
#define ID_SPRITE_MARIO_TANOOKI_JUMP_WALK_LEFT (ID_SPRITE_MARIO_TANOOKI_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_TANOOKI_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_TANOOKI_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_TANOOKI_JUMP_RUN (ID_SPRITE_MARIO_TANOOKI_JUMP + 20)
#define ID_SPRITE_MARIO_TANOOKI_JUMP_RUN_LEFT (ID_SPRITE_MARIO_TANOOKI_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_TANOOKI_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_TANOOKI_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_TANOOKI_SIT (ID_SPRITE_MARIO_TANOOKI + 500)
#define ID_SPRITE_MARIO_TANOOKI_SIT_LEFT (ID_SPRITE_MARIO_TANOOKI_SIT + 10)
#define ID_SPRITE_MARIO_TANOOKI_SIT_RIGHT (ID_SPRITE_MARIO_TANOOKI_SIT + 20)
#define ID_SPRITE_MARIO_TANOOKI_BRACE (ID_SPRITE_MARIO_TANOOKI + 600)
#define ID_SPRITE_MARIO_TANOOKI_BRACE_LEFT (ID_SPRITE_MARIO_TANOOKI_BRACE + 10)
#define ID_SPRITE_MARIO_TANOOKI_BRACE_RIGHT (ID_SPRITE_MARIO_TANOOKI_BRACE + 20)
#define ID_SPRITE_MARIO_TANOOKI_FLY (ID_SPRITE_MARIO_TANOOKI + 700)
#define ID_SPRITE_MARIO_TANOOKI_FLY_LEFT (ID_SPRITE_MARIO_TANOOKI_FLY + 10)
#define ID_SPRITE_MARIO_TANOOKI_FLY_RIGHT (ID_SPRITE_MARIO_TANOOKI_FLY + 20)
#define ID_SPRITE_MARIO_TANOOKI_SLOWDROP (ID_SPRITE_MARIO_TANOOKI + 800)
#define ID_SPRITE_MARIO_TANOOKI_SLOWDROP_LEFT (ID_SPRITE_MARIO_TANOOKI_SLOWDROP + 10)
#define ID_SPRITE_MARIO_TANOOKI_SLOWDROP_RIGHT (ID_SPRITE_MARIO_TANOOKI_SLOWDROP + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000
#define ID_SPRITE_GOLD_BRICK 20100
#define ID_SPRITE_INVI_BRICK 20200
#define ID_SPRITE_BASE_BRICK 20300
#define ID_SPRITE_PIPE 20400
#define ID_SPRITE_QUESTION_BRICK 20500
#define ID_SPRITE_NULL_BRICK 20600
#define ID_SPRITE_STRIPE_BRICK 20700

//define for question block's item id
#define ID_ITEM_COIN 1
#define ID_ITEM_MUSHROOM 2
#define ID_ITEM_TANOOKI 3

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 100)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 200)
#define ID_SPRITE_PARAGOOMBA 31000

#define ID_SPRITE_KOOPA (ID_SPRITE_GOOMBA + 3000)
#define ID_SPRITE_KOOPA_WALKING (ID_SPRITE_KOOPA + 100)
#define ID_SPRITE_KOOPA_SHELL (ID_SPRITE_KOOPA + 200)
#define ID_SPRITE_KOOPA_SHAKING (ID_SPRITE_KOOPA + 300)
#define ID_SPRITE_KOOPA_SPINNING (ID_SPRITE_KOOPA + 400)
#define ID_SPRITE_KOOPA_WALKING_RIGHT (ID_SPRITE_KOOPA + 500)
#define ID_SPRITE_PARAKOOPA (ID_SPRITE_KOOPA + 600)
#define ID_SPRITE_PARAKOOPA_RIGHT (ID_SPRITE_KOOPA + 700)

#define ID_SPRITE_COIN 40000
#define ID_SPRITE_BLOCK_COIN (ID_SPRITE_COIN + 100)
#define ID_SPRITE_MUSHROOM (ID_SPRITE_COIN + 1000)

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)
#define ID_SPRITE_BUTTON 52000

#define ID_SPRITE_ENVIRONMENT 60000

#define ID_SPRITE_FIRETRAP 70000
#define ID_SPRITE_GREEN_FIRETRAP 70100
#define ID_SPRITE_GREEN_FLYTRAP 70200
#define ID_SPRITE_FIREBALL 71000